{% set name = "sphinx-thebe" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-thebe-{{ version }}.tar.gz
  sha256: c22a3894e7f0131f420d1a4fd8bbd14b5b38ad4ed7ee57b1a0d9da03469be873

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sphinx >=1.8

test:
  imports:
    - sphinx_thebe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/sphinx-thebe
  summary: Add a copy button to each of your code cells.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anirrudh
    - chrisjsewell
