{% set name = "sphinx-thebe" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-thebe-{{ version }}.tar.gz
  sha256: 6229caa99e996776ffdc5c658d9dcce09e0c749727e5aa3d280a2bbf3a72068a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sphinx >=1.8

test:
  imports:
    - sphinx_thebe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/sphinx-thebe
  summary: Add a copy button to each of your code cells.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anirrudh
